#!/usr/bin/env bun

import { Glob } from "bun";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { VERSION } from "../src/version.ts";

const ROOT = join(import.meta.dir, "..");
const DASHBOARD_BUILD = join(ROOT, "dashboard/build");
const GENERATED = join(ROOT, "src/core/server/dashboard-assets.generated.ts");
const DIST = join(ROOT, "dist");
const OUTFILE = join(DIST, "bak");

function parseArgs(): { target?: string } {
  const args = process.argv.slice(2);
  let target: string | undefined;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--target" && args[index + 1]) {
      target = args[index + 1];
      index += 1;
    }
  }

  return { target };
}

async function buildDashboard(): Promise<void> {
  console.log("Building dashboard...");
  const proc = Bun.spawn(["bun", "run", "dashboard:build"], {
    cwd: ROOT,
    stdout: "inherit",
    stderr: "inherit",
  });
  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    throw new Error("Dashboard build failed");
  }
}

function collectDashboardFiles(): string[] {
  if (!existsSync(DASHBOARD_BUILD)) {
    throw new Error("Dashboard build not found at dashboard/build");
  }

  const glob = new Glob("**/*");
  const files: string[] = [];

  for (const file of glob.scanSync({ cwd: DASHBOARD_BUILD, onlyFiles: true })) {
    files.push(file.replace(/\\/g, "/"));
  }

  files.sort();
  return files;
}

function generateManifest(files: string[]): void {
  const imports: string[] = [];
  const entries: string[] = [];

  for (let index = 0; index < files.length; index += 1) {
    const file = files[index]!;
    const variable = `asset_${index}`;
    const importPath = `../../../dashboard/build/${file}`;
    imports.push(`import ${variable} from "${importPath}" with { type: "file" };`);
    entries.push(`  ${JSON.stringify(file)}: ${variable},`);
  }

  const content = `// Auto-generated by scripts/build.ts — do not edit manually.

${imports.join("\n")}

export const DASHBOARD_EMBEDDED = true;

export const DASHBOARD_ASSETS: Record<string, string> = {
${entries.join("\n")}
};
`;

  writeFileSync(GENERATED, content);
  console.log(`Generated dashboard manifest with ${files.length} assets`);
}

async function compileBinary(target?: string): Promise<void> {
  mkdirSync(DIST, { recursive: true });

  console.log(`Compiling binary${target ? ` (target: ${target})` : ""}...`);

  // Dashboard assets are embedded via imports in dashboard-assets.generated.ts.
  const result = await Bun.build({
    entrypoints: [join(ROOT, "src/index.ts")],
    compile: {
      outfile: OUTFILE,
      ...(target ? { target: target as Bun.Build.CompileTarget } : {}),
    },
    define: {
      BUILD_COMPILED: '"true"',
      BUILD_VERSION: JSON.stringify(VERSION),
    },
  });

  if (!result.success) {
    for (const log of result.logs) {
      console.error(log);
    }
    throw new Error("Binary compilation failed");
  }
}

async function main(): Promise<void> {
  const { target } = parseArgs();

  await buildDashboard();
  const files = collectDashboardFiles();
  generateManifest(files);
  await compileBinary(target);

  console.log(`Built ${relative(ROOT, OUTFILE)}`);
}

await main();
